### ISSUE TITLE
Can I change the prefix and command?

### ISSUE THREAD

**Issue by fleeting-fear** [krypton-byte/chappie-bot#11]
if I can changw the prefix and command,how to change?

**Comment by krypton-byte** [comment]
then you go to a main3.py and edit at var FullComand and edit all of these command with your prefix

**Comment by fleeting-fear** [comment]
> then you go to a main3.py and edit at var FullComand and edit all of these command with your prefix

okay,thank you very much

**Comment by fleeting-fear** [comment]
.
